DinoTools/python-overpy

README.rst, overpy/helper.py
* `get_street` and `get_intersection`
=> add helper methods

overpy/__init__.py, tests/test_xml.py
Add SAX parser to lower memory consumption. Fixes #15
=> New SAX parser

.travis.yml
=> test - Fix Travis builds on Python 3.2

setup.py, tox.ini
Add additional information about Python 3.5 to the classifiers and the tox envlist.
=> Python 3.5

overpy/__init__.py
Add url parameter to the Overpass class to set the URL for the API.
=> Add url param

examples/get_nodes.py, overpy/__init__.py, tests/base_class.py
Use attribute modifiers to convert some common attributes. For more information have a look at http://wiki.openstreetmap.org/wiki/Elements#Common_attributes
Inspired by #36
=> Add attribute modifiers

setup.py
=> Use utf-8 to read the readme file

MANIFEST.in, setup.cfg
Add a MANIFEST.in and a setup.cfg to provide additional build information.
This fixes #41
=> Additional build information

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.rst, docs/source/contributing.rst, docs/source/index.rst
Add GitHub templates and contributing info.
=> GitHub and Contributing

tests/__init__.py
- Bugfix
Use processes instead of threads because multiprocessing seams to be more reliable than threading. Fixes #49
=> test - Use processes instead of threads

CHANGELOG.rst, overpy/__about__.py, setup.cfg, setup.py, tests/__init__.py, tests/test_request.py, tests/test_result.py, tests/test_result_way.py
- Feature
Update changelog and bump version to release version 0.4
Fixes #45
=> Prepare release of version 0.4

docs/source/faq.rst, docs/source/index.rst, overpy/__init__.py, overpy/exception.py, tests/__init__.py, tests/test_request.py
- Feature
- Documentation
Wait some time if the TooManyRequests exception has been raised and try again.
=> Handle TooManyRequests exception

overpy/__init__.py, tests/test_result.py
- Feature
Add the feature to pickle and unpickle the Result() object.
Fixes #58
=> Pickle Result() object

overpy/exception.py
- Bugfix
Fixes #70 
Automatically trimmed trailing spaces and added ending `\n` when saving file.
=> #70: Change BaseException to Exception.

codeql-analysis.yml
- Feature
Add GitHub action for CodeQL security scan.
=> ci - Add CodeQL test

README.rst
- Bugfix
Replace old CI badge with new one from GitHub actions.  Fixes #84
=> Fix CI run badge in README

MANIFEST.in, setup.cfg, setup.py
- Feature
* Add missing files to package
* Move static content to static file
* Add URLs
=> Improve package build

CHANGELOG.rst, overpy/__about__.py
- Release
Prepare release of version 0.6
=> Release 0 6

.github/workflows/pypi.yml
- Feature
CI Pipeline to publish releases on PyPI.
=> Publish releases to PyPI

.github/config.yml, .github/stale.yml
- Feature
- Bugfix
- Documentation
- ...
=> Add github config for welcome and stale bot
